adicionando testes unitarios
betrybe/sd-0x-a-cli-of-ice-and-fire pull request #4
Opened 2020-08-06 14:30 UTC by brunobatista25

Adicionando os testes unitários dos requisitos
nos arquivos 
books.test.js
house.test.js

e foi adicionados pacotes extras necessários pra funcionar alguns pacotes existentes

2020-08-06 14:40 UTC, jeanpsv requested changes

2020-08-06 14:40 UTC, jeanpsv commented on package.json
> +    "coverageJson": "jest  --coverage --coverageReporters='json-summary' --testFailureExitCode=0",
Minha dúvida é só sobre esse ponto aqui:

Hj o avaliador executa esse `npm test`(https://github.com/betrybe/jest-evaluator-action/blob/master/entrypoint.sh#L11) apenas, não conseguimos chamar um `npm run converageJson`.

Não identifiquei no PR o requisito que fazer o teste da cobertura do código, é possível vc me apontar ele?

2020-08-06 14:40 UTC, jeanpsv commented on test/house.test.js
> +    describe.only('Exibir opção de listar as casas do mundo de Game of Thrones', () => {
```suggestion
    describe('Exibir opção de listar as casas do mundo de Game of Thrones', () => {
```

2020-08-06 14:40 UTC, jeanpsv commented on test/house.test.js
> +});
```suggestion
});

```

2020-08-06 14:56 UTC, brunobatista25 commented on package.json
> +    "coverageJson": "jest  --coverage --coverageReporters='json-summary' --testFailureExitCode=0",
opa jean nao subi ele ainda pq temos que conversar sobre ele

2020-08-06 14:57 UTC, brunobatista25 commented on package.json
> +    "coverageJson": "jest  --coverage --coverageReporters='json-summary' --testFailureExitCode=0",
mas seria isso aqui oh
        shell.exec('npm run coverageJson')
        let fileCoverage = fs.readFileSync('./coverage/coverage-summary.json');        
        let parseFileCoverage = JSON.parse(fileCoverage);
        expect(parseFileCoverage.total.lines.pct).toEqual('90.00')

2020-08-06 15:01 UTC, jeanpsv commented on package.json
> +    "coverageJson": "jest  --coverage --coverageReporters='json-summary' --testFailureExitCode=0",
@brunobatista25 boa, falamos sobre ele, legal

2020-08-06 20:33 UTC, jeanpsv approved these changes

2020-08-07 16:49 UTC, inaC requested changes

2020-08-07 16:49 UTC, inaC commented on test/books.test.js
> +        });
Você não está usando `await` dentro da callback, logo você poderia remover a keyword `async`, não?

2020-08-07 16:49 UTC, inaC commented on test/books.test.js
> +        test('Digitar nome do livro em branco e ver se a API é chamada passando o parâmetro "nome" em branco', async () => {
Você precisa definir a callback com `async`?

2020-08-07 16:49 UTC, inaC commented on test/books.test.js
> +        test('Ver se retorna todos os livros paginados', async () => {
Você precisa definir a callback com `async`?

2020-08-07 16:49 UTC, inaC commented on test/books.test.js
> +        test('Verificar a presença da opção "Próxima página" na lista de livros', async () => {
Você precisa definir a callback com `async`?

2020-08-07 16:49 UTC, inaC commented on test/books.test.js
> +        test('Selecionar livro "A Clash of Kings" e verificar que seus dados apresentados estão corretos', async () => {
Você precisa definir a callback com `async`?

2020-08-07 16:49 UTC, inaC commented on test/books.test.js
> +        test('Verificar a presença da opção "Voltar para o menu principal" no menu de livros', async () => {
Você precisa definir a callback com `async`?

2020-08-07 16:49 UTC, inaC commented on test/books.test.js
> +        test('verificar a presença da opção "Voltar para o menu anterior" e "Página anterior" no menu de "Listar livros na página seguinte"', async () => {
```suggestion
        test('Verificar a presença da opção "Voltar para o menu anterior" e "Página anterior" no menu de "Listar livros na página seguinte"', async () => {
```

2020-08-07 16:49 UTC, inaC commented on test/books.test.js
> +            test('Enviar um nome de livro que não existe e verificar que a mensagem "Nenhum livro encontrado para essa pesquisa"  é exibida na tela posteriormente', async () => {
```suggestion
            test('Enviar um nome de livro que não existe e verificar que a mensagem "Nenhum livro encontrado para essa pesquisa" é exibida na tela posteriormente', async () => {
```

2020-08-07 16:49 UTC, inaC commented on test/books.test.js
> +
```suggestion
```

2020-08-07 16:49 UTC, inaC commented on test/books.test.js
> +        test("Verificar se, quando escolho  o livro 'A Game of Thrones', ele chama a API e mostra os dados do livro, em seguida mostrando a lista dos outros livros", async () => {
```suggestion
        test("Verificar se, quando escolho o livro 'A Game of Thrones', ele chama a API e mostra os dados do livro, em seguida mostrando a lista dos outros livros", async () => {
```

2020-08-07 16:49 UTC, inaC commented on test/fixtures/books.js
> +const firstPageBody = [
Esse arquivo está formatado de acordo? O syntax highlighting do github para javascript não está funcionando  , enquanto que para `test/fixtures/houses.js` o highlight funcionou 🤔

2020-08-07 16:49 UTC, inaC commented on test/fixtures/houses.js
> +};
```suggestion
};

```

2020-08-07 16:49 UTC, inaC commented on test/house.test.js
> +        test('verificar se existe a opcao "casas" no menu inicial', async () => {
```suggestion
        test('Verificar se existe a opção "casas" no menu inicial', async () => {
```

2020-08-07 16:49 UTC, inaC commented on test/house.test.js
> +        test('Ao selecionar casas verificar se existe a opcao "listar casas"', async () => {
```suggestion
        test('Ao selecionar casas verificar se existe a opção "listar casas"', async () => {
```

2020-08-07 16:49 UTC, inaC commented on test/house.test.js
> +        test('Ao selecionar casas verificar se existe a opcao "listar casas"', async () => {
Você precisa definir a callback com `async`?

2020-08-07 16:49 UTC, inaC commented on test/house.test.js
> +        test('Verificar a opcao "Próxima página"', async () => {
```suggestion
        test('Verificar a opção "Próxima página"', async () => {
```

2020-08-07 16:49 UTC, inaC commented on test/house.test.js
> +        test('Verificar a opcao "Página anterior" quando vou para proxima pagina', async () => {
```suggestion
        test('Verificar a opção "Página anterior" quando vou para próxima página', async () => {
```

2020-08-07 16:49 UTC, inaC commented on test/books.test.js
> +        test('Verificar a presença da opção "Página anterior" quando vou para próxima página na lista de livros', async () => {
Você precisa definir a callback com `async`?

2020-08-07 16:49 UTC, inaC commented on test/books.test.js
> +
```suggestion
```

2020-08-07 16:49 UTC, inaC commented on test/books.test.js
> +        test("Verificar se, quando escolho  o livro 'A Game of Thrones', ele chama a API e mostra os dados do livro, em seguida mostrando a lista dos outros livros", async () => {
Você precisa definir a callback com `async`?

2020-08-07 18:37 UTC, brunobatista25 commented on test/fixtures/books.js
> +const firstPageBody = [
ta sim mano,aprece q quando e muito grande ele nao funciona

2020-08-07 18:39 UTC, inaC commented on test/fixtures/books.js
> +    { "url": "https://www.anapioficeandfire.com/api/books/1", "name": "A Game of Thrones", "isbn": "978-0553103540", "authors": ["George R. R. Martin"], "numberOfPages": 694, "publisher": "Bantam Boo
```suggestion
};

```

2020-08-07 18:56 UTC, inaC approved these changes

2020-08-07 18:58 UTC, merged